apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kanban
  namespace: itmo
spec:
  rules:
  - host: kanban-board.itmo.org
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: kanban-ui
              port:
                number: 4200
                